on: [push, pull_request]

name: Actions CI + Docs

jobs:
  build_and_test:
    name: uvco
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang++, g++-14]
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run:  |
          sudo apt-get update
          sudo apt-get install -y clang g++-14 cmake ninja-build libfmt-dev libuv1-dev libgtest-dev libboost-dev libboost-log-dev libboost-program-options-dev libcurl-dev
      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake -GNinja -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} ..
          ninja
          ctest --output-on-failure
